version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: miprimerabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  spring_boot_app:
    image: openjdk:17
    container_name: spring_boot_app
    volumes:
      - ./.mvn/wrapper/maven-wrapper.jar:/app/mi-aplicacion-spring-boot.jar
    command: ["java", "-jar", "/app/mi-aplicacion-spring-boot.jar"]

volumes:
  mysql_data:
